CREATE TABLE server_info (
    id                BIGINT AUTO_INCREMENT PRIMARY KEY,
    parent_id         BIGINT COMMENT '父服务器ID',
    server_name       VARCHAR(120) NOT NULL COMMENT '服务器名称',
    server_type       TINYINT DEFAULT 1 COMMENT '1-服务器 2-云数据库',
    connection_type   TINYINT DEFAULT 1 COMMENT '1-SSH连接 2-直连',
    cloud_vendor      VARCHAR(100) COMMENT '云服务商',
    ip                VARCHAR(255) NOT NULL COMMENT 'IP/域名',
    ssh_port          INT DEFAULT 22 COMMENT 'SSH端口',
    username          VARCHAR(100) COMMENT 'SSH用户名',
    password          VARCHAR(255) COMMENT 'SSH密码',
    private_key       TEXT COMMENT '私钥内容',
    private_key_path  VARCHAR(500) COMMENT '私钥路径',
    public_key        TINYINT DEFAULT 0 COMMENT '公钥是否已配置 0否1是',
    public_key_value  TEXT COMMENT '公钥内容',
    ms_user           VARCHAR(100) COMMENT 'MySQL用户名',
    ms_pwd            VARCHAR(255) COMMENT 'MySQL密码',
    ms_port           INT DEFAULT 3306 COMMENT 'MySQL端口',
    database_name     VARCHAR(120) DEFAULT 'im_platform' COMMENT '数据库名',
    docker_api_port   INT COMMENT 'Docker API端口',
    sp_link           TEXT COMMENT '超链接',
    status            TINYINT DEFAULT 0 COMMENT '服务器状态 1正常0异常',
    sort_order        INT DEFAULT 0 COMMENT '排序',
    del_flag          TINYINT DEFAULT 0 COMMENT '软删除',
    create_time       DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time       DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_server_parent (parent_id),
    INDEX idx_server_name (server_name),
    INDEX idx_server_ip (ip),
    INDEX idx_server_del_flag (del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE server_info_log (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    server_id       BIGINT COMMENT '服务器ID',
    server          VARCHAR(255) COMMENT '服务器IP/域名',
    task            VARCHAR(120) COMMENT '任务名',
    log             MEDIUMTEXT COMMENT '执行日志',
    status          TINYINT DEFAULT 1 COMMENT '1成功0失败',
    start_time      DATETIME COMMENT '开始时间',
    end_time        DATETIME COMMENT '结束时间',
    duration        VARCHAR(60) COMMENT '任务时长',
    operator_id     BIGINT COMMENT '操作人',
    create_time     DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_server_log_server_id (server_id),
    INDEX idx_server_log_status (status),
    INDEX idx_server_log_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE docker_service (
    id                BIGINT AUTO_INCREMENT PRIMARY KEY,
    server_id         BIGINT NOT NULL COMMENT '所属服务器ID',
    service_name      VARCHAR(120) NOT NULL COMMENT '服务名',
    container_name    VARCHAR(120) COMMENT '容器名',
    hostname          VARCHAR(120) COMMENT '主机名',
    image_name        VARCHAR(255) NOT NULL COMMENT '镜像名',
    current_version   VARCHAR(100) COMMENT '当前版本',
    target_version    VARCHAR(100) COMMENT '目标版本',
    ports             JSON COMMENT '端口映射数组',
    environment       JSON COMMENT '环境变量数组',
    volumes           JSON COMMENT '数据卷数组',
    depends_on        JSON COMMENT '依赖服务数组',
    networks          JSON COMMENT '网络配置',
    restart_policy    VARCHAR(50) COMMENT '重启策略',
    command           TEXT COMMENT '启动命令',
    extra_config      JSON COMMENT '扩展配置',
    use_params_mode   TINYINT DEFAULT 0 COMMENT '是否PARAMS模式',
    status            TINYINT DEFAULT 0 COMMENT '0停止1运行2异常',
    del_flag          TINYINT DEFAULT 0 COMMENT '软删除',
    create_time       DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time       DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_docker_service_server_id (server_id),
    INDEX idx_docker_service_status (status),
    UNIQUE KEY uk_docker_service_name (server_id, service_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE docker_task (
    id                BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_type         VARCHAR(50) NOT NULL COMMENT '任务类型',
    server_id         BIGINT NOT NULL COMMENT '服务器ID',
    service_ids       JSON COMMENT '服务ID列表',
    service_names     TEXT COMMENT '服务名称列表',
    status            TINYINT DEFAULT 0 COMMENT '0待处理1处理中2完成3失败',
    total_count       INT DEFAULT 0,
    success_count     INT DEFAULT 0,
    fail_count        INT DEFAULT 0,
    current_service   VARCHAR(120) COMMENT '当前处理服务',
    progress_percent  INT DEFAULT 0 COMMENT '进度百分比',
    error_message     TEXT COMMENT '错误消息',
    result_detail     JSON COMMENT '结果详情',
    finish_time       DATETIME COMMENT '完成时间',
    create_time       DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time       DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_docker_task_server_id (server_id),
    INDEX idx_docker_task_status (status),
    INDEX idx_docker_task_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE docker_compose_file (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    server_id       BIGINT NOT NULL COMMENT '服务器ID',
    file_name       VARCHAR(255) NOT NULL COMMENT '文件名',
    file_content    MEDIUMTEXT COMMENT 'Compose内容',
    file_path       VARCHAR(500) COMMENT '文件路径',
    version         VARCHAR(50) COMMENT 'compose版本',
    parse_status    TINYINT DEFAULT 0 COMMENT '0未解析1已解析2失败',
    parse_error     TEXT COMMENT '解析错误',
    create_time     DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_compose_server_id (server_id),
    INDEX idx_compose_parse_status (parse_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
